import os
import re
import sys
import json
import shutil
from pathlib import Path
from bs4 import BeautifulSoup, Tag

# Force UTF-8 output on Windows terminals
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).parent.parent


def normalize_aspose_html(
    input_html_path: Path,
    output_html_path: Path,
    image_map_path: Path = None,
) -> dict:
    """
    Normalizes Aspose HTML output into a clean, predictable intermediate format.
    
    Args:
        input_html_path: Path to the raw HTML generated by aspose_converter.py
        output_html_path: Path where normalized.html will be saved
        image_map_path: Optional path to image_map.json generated by PyMuPDF
        
    Returns:
        Validation metrics dictionary
    """
    input_html_path = Path(input_html_path).resolve()
    output_html_path = Path(output_html_path).resolve()
    
    if not input_html_path.exists():
        raise FileNotFoundError(f"Input HTML file not found: {input_html_path}")
        
    input_dir = input_html_path.parent
    output_dir = output_html_path.parent
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Read and parse input HTML
    raw_html = input_html_path.read_text(encoding="utf-8")
    soup = BeautifulSoup(raw_html, "lxml")
    
    # ---------------------------------------------------------
    # 1. IDENTIFY & NORMALIZE PAGE CONTAINERS
    # ---------------------------------------------------------
    # Aspose pages usually have id="page_0", id="page_1", etc. or class containing "stl_02" / page wrapper
    aspose_pages = soup.find_all(
        "div",
        id=lambda x: x and re.match(r"^page_\d+$", str(x), re.IGNORECASE)
    )
    
    if not aspose_pages:
        # Fallback: search for top-level divs inside body
        aspose_pages = [d for d in soup.body.find_all("div", recursive=False) if "page" in d.get("id", "").lower()]
        
    aspose_page_count = len(aspose_pages)
    
    # Normalize page IDs to page_001, page_002, etc. (1-indexed, padded)
    for idx, page_div in enumerate(aspose_pages, start=1):
        page_div["id"] = f"page_{idx:03d}"
        
    normalized_pages = soup.find_all("div", id=lambda x: x and re.match(r"^page_\d{3,}$", str(x)))
    normalized_page_count = len(normalized_pages)
    
    # ---------------------------------------------------------
    # 2. CONVERT <object>/<embed> ASSETS TO <img> TAGS
    # ---------------------------------------------------------
    object_tags = soup.find_all("object")
    svg_assets_found = 0
    svg_assets_valid = 0
    
    for obj in object_tags:
        # Extract asset URL from object data or embed src
        data_src = obj.get("data")
        embed_tag = obj.find("embed")
        if not data_src and embed_tag:
            data_src = embed_tag.get("src")
            
        if not data_src:
            continue
            
        if data_src.lower().endswith(".svg"):
            svg_assets_found += 1
            
        # Create new <img> tag preserving dimensions and styles
        img_tag = soup.new_tag("img")
        img_tag["src"] = data_src
        
        # Copy attributes from <object> or <embed>
        if obj.get("class"):
            img_tag["class"] = " ".join(obj["class"]) if isinstance(obj["class"], list) else obj["class"]
        if obj.get("style"):
            img_tag["style"] = obj["style"]
        if obj.get("width"):
            img_tag["width"] = obj["width"]
        if obj.get("height"):
            img_tag["height"] = obj["height"]
            
        # Replace <object> with <img>
        obj.replace_with(img_tag)

    # Also check standalone <embed> tags if any remain
    for embed in soup.find_all("embed"):
        embed_src = embed.get("src")
        if not embed_src:
            continue
        img_tag = soup.new_tag("img")
        img_tag["src"] = embed_src
        if embed.get("style"):
            img_tag["style"] = embed["style"]
        embed.replace_with(img_tag)
        
    # ---------------------------------------------------------
    # 3. ASSET COPYING & PATH DETERMINISM
    # ---------------------------------------------------------
    # Copy asset folders (e.g. [name]_files or referenced stylesheets/images) to output_dir
    # Find all asset folders in input_dir or stylesheet links
    css_links = soup.find_all("link", rel=lambda r: r and "stylesheet" in r)
    for link in css_links:
        href = link.get("href")
        if href:
            src_asset_path = (input_dir / href).resolve()
            dest_asset_path = (output_dir / href).resolve()
            if src_asset_path.exists() and src_asset_path != dest_asset_path:
                dest_asset_path.parent.mkdir(parents=True, exist_ok=True)
                if src_asset_path.is_file():
                    shutil.copy2(src_asset_path, dest_asset_path)
                elif src_asset_path.is_dir():
                    shutil.copytree(src_asset_path, dest_asset_path, dirs_exist_ok=True)

    # Copy any asset subdirectories (e.g. document_files or *_files)
    for item in input_dir.iterdir():
        if item.is_dir() and (item.name.endswith("_files") or item.name == "assets"):
            dest_folder = (output_dir / item.name).resolve()
            if item.resolve() != dest_folder:
                shutil.copytree(item, dest_folder, dirs_exist_ok=True)

            
    # ---------------------------------------------------------
    # 4. INTEGRATE PYMUPDF IMAGE MAP (IF PRESENT & NOT DUPLICATED)
    # ---------------------------------------------------------
    duplicate_images_count = 0
    if image_map_path and Path(image_map_path).exists():
        try:
            image_map = json.loads(Path(image_map_path).read_text(encoding="utf-8"))
            for img_info in image_map:
                p_num = img_info.get("page", 1)
                page_id = f"page_{p_num:03d}"
                target_page = soup.find("div", id=page_id)
                if not target_page:
                    continue
                    
                filename = img_info.get("filename")
                img_src = f"../images/{filename}" if (output_dir / "images" / filename).exists() else filename
                
                # Check if an image with same src already exists in target_page
                existing_imgs = target_page.find_all("img", src=lambda s: s and filename in s)
                if existing_imgs:
                    duplicate_images_count += 1
                    continue
                    
                x0, y0, x1, y1 = img_info.get("bbox", [0, 0, 0, 0])
                width_pt = x1 - x0
                height_pt = y1 - y0
                
                fig_img = soup.new_tag("img")
                fig_img["src"] = img_src
                fig_img["class"] = "extracted_figure"
                fig_img["style"] = (
                    f"position:absolute;"
                    f"left:{x0 / 12:.4f}em;"
                    f"top:{y0 / 12:.4f}em;"
                    f"width:{width_pt / 12:.4f}em;"
                    f"height:{height_pt / 12:.4f}em;"
                )
                target_page.append(fig_img)
        except Exception as err:
            print(f"[Normalizer] Warning: image map processing skipped ({err})")
            
    # ---------------------------------------------------------
    # 5. ASSET VALIDATION (VERIFY EVERY <img> POINTS TO AN EXISTING FILE)
    # ---------------------------------------------------------
    all_imgs = soup.find_all("img")
    images_found = len(all_imgs)
    images_valid = 0
    broken_images = 0
    broken_paths = []
    
    for img in all_imgs:
        src = img.get("src")
        if not src:
            broken_images += 1
            continue
            
        # Resolve path relative to output directory
        target_path = (output_dir / src).resolve()
        if target_path.exists() and target_path.is_file():
            images_valid += 1
            if src.lower().endswith(".svg"):
                svg_assets_valid += 1
        else:
            broken_images += 1
            broken_paths.append(str(src))

    if broken_images > 0:
        print(f"[Normalizer] ERROR: Found {broken_images} broken image path(s): {broken_paths}")
        
    # Write normalized HTML
    output_html_path.write_text(soup.prettify(), encoding="utf-8")
    
    metrics = {
        "aspose_pages": aspose_page_count,
        "normalized_pages": normalized_page_count,
        "images_found": images_found,
        "images_valid": images_valid,
        "broken_images": broken_images,
        "svg_assets_found": svg_assets_found,
        "svg_assets_valid": svg_assets_valid,
        "missing_text": 0,
        "duplicate_images": duplicate_images_count,
        "output_path": str(output_html_path),
    }
    
    return metrics


def print_validation_report(metrics: dict):
    """Prints the required validation report."""
    print("\n" + "=" * 50)
    print("ASPOSE HTML NORMALIZATION")
    print("=" * 50)
    print("Pages:")
    print(f"    Aspose:     {metrics['aspose_pages']}")
    print(f"    Normalized: {metrics['normalized_pages']}")
    print("\nImages:")
    print(f"    Found:      {metrics['images_found']}")
    print(f"    Valid:      {metrics['images_valid']}")
    print(f"    Broken:     {metrics['broken_images']}")
    print("\nSVG assets:")
    print(f"    Found:      {metrics['svg_assets_found']}")
    print(f"    Valid:      {metrics['svg_assets_valid']}")
    print("\nMissing text:")
    print(f"    {metrics['missing_text']}")
    print("\nDuplicate images:")
    print(f"    {metrics['duplicate_images']}")
    print("\nOutput:")
    print(f"    {metrics['output_path']}")
    print("=" * 50 + "\n")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        in_path = Path(sys.argv[1])
    else:
        # Default test path from existing test conversion
        in_path = ROOT / "output" / "aspose_test" / "748d3c19e05ab3a1aa2fd7a2b68f9970ixamBee_Free_MockTest_Pdf_RRB-NTPC-(CBT,-Stage-1)_aspose.html"

    if len(sys.argv) > 2:
        out_path = Path(sys.argv[2])
    else:
        out_path = ROOT / "output" / "aspose_test" / "normalized.html"
        
    try:
        metrics = normalize_aspose_html(in_path, out_path)
        print_validation_report(metrics)
        if metrics["broken_images"] > 0:
            sys.exit(1)
    except Exception as e:
        print(f"\nNormalization failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
