"""
mysql_setup.py
One-time setup script — run this ONCE before using the pipeline.

What it does:
  1. Adds  html_status TINYINT DEFAULT 0  to tbl_studymaterial_lang_map
  2. Creates the  tbl_html_to_pdf  logging table

Run from workspace root:
    python scripts/mysql_setup.py
"""

import sys
from pathlib import Path

scripts_dir = Path(__file__).parent
if str(scripts_dir) not in sys.path:
    sys.path.append(str(scripts_dir))

from mysql_client import get_connection


def add_status_column():
    """Add html_status column to the source table (safe if already exists)."""
    conn = get_connection()
    cursor = conn.cursor()

    try:
        cursor.execute("""
            ALTER TABLE tbl_studymaterial_lang_map
            ADD COLUMN html_status TINYINT NOT NULL DEFAULT 0
        """)
        conn.commit()
        print("[Setup] OK  Added column: tbl_studymaterial_lang_map.html_status")
    except Exception as e:
        if "Duplicate column" in str(e) or "already exists" in str(e).lower():
            print("[Setup] INFO Column html_status already exists -- skipping")
        else:
            cursor.close()
            conn.close()
            raise

    cursor.close()
    conn.close()


def create_automation_table():
    """Create the tbl_html_to_pdf logging table."""
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS tbl_html_to_pdf (
            pdf_id                  INT          AUTO_INCREMENT PRIMARY KEY,
            mysql_id                INT          NOT NULL UNIQUE,
            original_pdf            VARCHAR(1000)           COMMENT 'Download URL of the source PDF',
            pdf_html_format         VARCHAR(1000)           COMMENT 'Local path to the converted HTML file',
            output_html             VARCHAR(1000)           COMMENT 'Local path to the final Gemini-processed output.html',
            html_content            LONGTEXT                COMMENT 'Full HTML content (with tags) of the final output',
            status                  VARCHAR(50)  DEFAULT 'DOWNLOADED'
                                                            COMMENT 'DOWNLOADED | HTML_READY | PROCESSING | COMPLETED | FAILED',
            processing_started_at   DATETIME     DEFAULT NULL COMMENT 'When pipeline.py --process started on this document',
            processing_completed_at DATETIME     DEFAULT NULL COMMENT 'When the output.html was successfully written',
            created_on              DATETIME     DEFAULT CURRENT_TIMESTAMP,
            created_by              VARCHAR(100) DEFAULT 'system',
            updated_on              DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            updated_by              VARCHAR(100) DEFAULT 'system',
            INDEX idx_status   (status),
            INDEX idx_mysql_id (mysql_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    """)
    conn.commit()
    print("[Setup] OK  Table ready: tbl_html_to_pdf")

    cursor.close()
    conn.close()


def add_processing_time_columns():
    """Safely add processing_started_at, processing_completed_at, script_html, and gemini columns."""
    conn   = get_connection()
    cursor = conn.cursor()
    for col, definition in [
        ("processing_started_at",   "DATETIME DEFAULT NULL COMMENT 'When pipeline --process started'"),
        ("processing_completed_at", "DATETIME DEFAULT NULL COMMENT 'When output.html was written'"),
        ("script_html",             "LONGTEXT COMMENT 'HTML generated by python script (pdf_html.py)'"),
        ("gemini",                  "LONGTEXT COMMENT 'HTML generated by Gemini pipeline'"),
    ]:
        try:
            cursor.execute(
                f"ALTER TABLE tbl_html_to_pdf ADD COLUMN {col} {definition}"
            )
            conn.commit()
            print(f"[Setup] OK  Added column: tbl_html_to_pdf.{col}")
        except Exception as e:
            if "Duplicate column" in str(e) or "already exists" in str(e).lower():
                print(f"[Setup] INFO Column {col} already exists -- skipping")
            else:
                cursor.close()
                conn.close()
                raise
    cursor.close()
    conn.close()



if __name__ == "__main__":
    print("=" * 60)
    print("MySQL Setup — PDF Automation Pipeline")
    print("=" * 60)

    try:
        add_status_column()
        create_automation_table()
        add_processing_time_columns()
        print("\n[Setup] SUCCESS All database objects are ready.")
    except Exception as e:
        print(f"\n[Setup] FAILED Error setting up database: {e}")
        sys.exit(1)
